name: Build and deploy to pages
on:
  # push:
  #   branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Minify source files
        shell: bash
        run: bash ".github/script.sh"
      - name: Configure GitHub pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload GitHub pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: 'pages'
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
